version: "3.1"

services:
  dc1:
    image: samba-ad-dc:almalinux
    environment:
      REALM: DGS.NET
      SEARCH_DOMAIN: dgs.net
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      SERVER_ROLE: dc
      DNS_BACKEND: SAMBA_INTERNAL
    command: bash -c "samba-domain-provision && samba -F"
    volumes:
      - usr-local-samba:/usr/local/samba
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445

  dc2:
    image: samba-ad-dc:ubuntu
    hostname: DC2
    privileged: true
    environment:
      REALM: DGS.NET
      SEARCH_DOMAIN: dgs.net
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      SERVER_ROLE: dc
      DNS_BACKEND: SAMBA_INTERNAL
    command: bash -c "samba-domain-join && samba -F"
    volumes:
      - var-lib-samba:/var/lib/samba

volumes:
  usr-local-samba:
  var-lib-samba:
