version: "3.8"

services:
  dc1:
    image: samba:almalinux
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/almalinux
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.10
      - 172.16.238.20
      - 172.16.238.30
      - 172.16.238.40
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: bash -c "samba-domain-provision && samba -F"
    volumes:
      - dc1-etc:/usr/local/samba/etc
      - dc1-private:/usr/local/samba/private
      - dc1-var:/usr/local/samba/var

    networks:
      static-network:
        ipv4_address: 172.16.238.10

  dc2:
    image: samba:ubuntu
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/ubuntu
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc2
    hostname: DC2
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.20
      - 172.16.238.30
      - 172.16.238.40
      - 172.16.238.10
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: bash -c "samba-domain-join DC1 && samba -F"
    volumes:
      - dc2-etc:/usr/local/samba/etc
      - dc2-private:/usr/local/samba/private
      - dc2-var:/usr/local/samba/var
    networks:
      static-network:
        ipv4_address: 172.16.238.20

  dc3:
    image: samba:rockylinux
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/rockylinux
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc3
    hostname: DC3
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.30
      - 172.16.238.40
      - 172.16.238.10
      - 172.16.238.20
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: bash -c "samba-domain-join DC1 && samba -F"
    volumes:
      - dc3-etc:/usr/local/samba/etc
      - dc3-private:/usr/local/samba/private
      - dc3-var:/usr/local/samba/var
    networks:
      static-network:
        ipv4_address: 172.16.238.30

  dc4:
    image: samba:debian
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/debian
      args:
        SMB_VERSION: "${SMB_VERSION:-latest}"
    container_name: dc4
    hostname: DC4
    privileged: true
    environment:
      REALM: DGS.NET
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      BIND_NETWORK_INTERFACES: false
    dns_search: dgs.net
    dns:
      - 172.16.238.40
      - 172.16.238.10
      - 172.16.238.20
      - 172.16.238.30
    extra_hosts:
      - "DC1 DC1.dgs.net:172.16.238.10"
      - "DC2 DC2.dgs.net:172.16.238.20"
      - "DC3 DC3.dgs.net:172.16.238.30"
      - "DC4 DC4.dgs.net:172.16.238.40"
    command: bash -c "samba-domain-join DC1 && samba -F"
    volumes:
      - dc4-etc:/usr/local/samba/etc
      - dc4-private:/usr/local/samba/private
      - dc4-var:/usr/local/samba/var
    networks:
      static-network:
        ipv4_address: 172.16.238.40

volumes:
  dc1-etc:
  dc1-private:
  dc1-var:
  dc2-etc:
  dc2-private:
  dc2-var:
  dc3-etc:
  dc3-private:
  dc3-var:
  dc4-etc:
  dc4-private:
  dc4-var:


networks:
  static-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24
