version: "3.1"

services:
  dc1:
    image: samba:almalinux
    restart: unless-stopped
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.almalinux
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: DGS.LOCAL
      SEARCH_DOMAIN: dgs.local
      DOMAIN: DGS
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
      SERVER_ROLE: dc
      DNS_BACKEND: SAMBA_INTERNAL
    command: bash -c "
      samba-domain-provision &&
      samba -F"
    volumes:
      - dc1-local-samba:/usr/local/samba

volumes:
  dc1-local-samba: